owner: distrochooser # GitHub username
repo: status # GitHub repository name
sites: # List of endpoints to track
  - name: Distrochooser Frontend
    url: https://distrochooser.de
  - name: Distrochooser Backend
    url: https://waldorf5.distrochooser.de/
    expectedStatusCodes:
      - 404  
  - name: Distrochooser Frontend (beta)
    url: https://beta.distrochooser.de
  - name: Distrochooser Backend (beta)
    url: https://waldorfbeta.distrochooser.de/
    expectedStatusCodes:
      - 404
assignees: # Users to assign downtime issues (optional)
  - cmllr
status-website:
  baseUrl: /status
  name: Distrochooser status  
  introTitle: "System status of the distrochooser.de project"
  introMessage: "System overview for distrochooser.de"
