owner: distrochooser # GitHub username
repo: distrochooser # GitHub repository name
sites: # List of endpoints to track
  - name: Distrochooser Frontend
    url: https://distrochooser.de
  - name: Distrochooser Backend
    url: https://waldorf5.distrochooser.de/ssrdata/de/
assignees: # Users to assign downtime issues (optional)
  - cmllr
status-website:
  baseUrl: /status # where "repo" is your repository name
  name: Distrochooser status
